### ISSUE TITLE
crashes when adding an account

### ISSUE THREAD

**Issue by DC7IA** [wakingrufus/mastodon-jfx#15]
Tried installing and using mastodon-jfx, but it only crashes.

`com.sys1yagi.mastodon4j.api.exception.Mastodon4jRequestException: Internal Server Error
	at com.sys1yagi.mastodon4j.api.method.Streaming.user(Streaming.kt:254)
	at com.github.wakingrufus.mastodon.account.CreateAccountStateKt.monitorUserFeeds(CreateAccountState.kt:110)
	at com.github.wakingrufus.mastodon.account.CreateAccountStateKt$createAccountState$1.doResume(CreateAccountState.kt:46)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by wakingrufus** [comment]
which instance is the account on? It looks like this may be a problem with the streaming API. perhaps that server has it disabled, or perhaps my client library needs to be updated. If i can reproduce it on the same instance, it might make it easier to narrow down.
Thank you for submitting this report!

**Comment by DC7IA** [comment]
I'm sure three years later it is no longer relevant, closing.
